---
title: "Conclusion_Report"
author: "Socorro Dominguez and Paul Vial"
date: '2018-11-16'
output: pdf_document
---










# **instructions from th assignment**: an .Rmd or .ipynb actually, that presents original data, the statistical summaries, and/or the figures in a little report. There should be a written narrative in this document that introduces and justifies your question, introduces the data set, presents the findings/results, and interprets the findings/results in context of the question. Some critique of the analysis is also expected (limitations, assumptions, etc) and a statement of future directions (what would you do next if you had more time to work on this). The report is expected to be 1-2 written pages (excluding figures, tables and references). You are expected to have a reference section and cite 2-3 external sources (data source can be one of these citations).

# **note from Tiffany**: In the report, all tables need a number and description (e.g., Table 1. Estimates and confidence intervals), and all figures need a figure number and legend (e.g., Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.) 